name: alice
description: Alice is an HTTP Inspector tool which helps debugging http requests. It catches and stores http requests and responses, which can be viewed via simple UI.
version: 0.4.2
#author: Jakub Homlala <jhomlala@gmail.com>
homepage: https://github.com/jhomlala/alice

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.5.0
  dio: ^5.9.0
  flutter_local_notifications: ^19.4.0
  rxdart: ^0.28.0
  path_provider: ^2.1.5
  permission_handler: ^12.0.1
  package_info_plus: ^8.3.1
  open_filex: ^4.7.0
  sensors_plus: ^6.1.2
  share_plus: ^11.1.0
  chopper: ^8.3.0
  collection: ^1.19.1
  url_launcher: ^6.3.2

dev_dependencies:
  very_good_analysis: ^9.0.0
